apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app }}
    component: {{ .Values.frontend.servicename }}
    env: {{ .Values.env }}
    role: {{ .Values.role }}

  name: {{ .Values.frontend.servicename }}
spec:
  #clusterIP: 10.98.171.1
  ports:
    - name: 2019-tcp
      protocol: TCP
      port: 2019
      targetPort: 2019
    - name: 443-tcp
      protocol: TCP
      port: 443
      targetPort: 443
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 80
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.app }}
    component: {{ .Values.frontend.name }}
    env: {{ .Values.env }}
    role: {{ .Values.role }}
  sessionAffinity: None
  #type: ClusterIP
status:
  loadBalancer: {}
